---
kind: pipeline
name: Codequality
steps:
- commands:
  - php -v
  - composer update
  - composer require phpmd/phpmd phpstan/phpstan
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards
  - vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/
  depends:
  - composer
  image: joomlaprojects/docker-images:php7.4
  name: phpcs
- commands:
  - vendor/bin/phpmd src text cleancode
  - vendor/bin/phpmd src text codesize
  - vendor/bin/phpmd src text controversial
  - vendor/bin/phpmd src text design
  - vendor/bin/phpmd src text unusedcode
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php7.4
  name: phpmd
- commands:
  - vendor/bin/phpstan analyse src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php7.4
  name: phpstan
- commands:
  - phploc src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php7.4
  name: phploc
- commands:
  - phpcpd src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php7.4
  name: phpcpd
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 7.2 lowest
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable --prefer-lowest
  image: joomlaprojects/docker-images:php7.2
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php7.2
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 7.2
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.2
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php7.2
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 7.3
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.3
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php7.3
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 7.4
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.0
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.0
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.0
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.0
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.1
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.0
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.2
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  failure: ignore
  image: joomlaprojects/docker-images:php8.2
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: signature
hmac: 479f44e580eacbe1c3319e8e2e9add9cd5254478e78d0db56086f0c18c68a621

...
